# Copyright 2022 Thales DIS design services SAS
#
# Licensed under the Solderpad Hardware Licence, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# SPDX-License-Identifier: Apache-2.0 WITH SHL-2.0
# You may obtain a copy of the License at https://solderpad.org/licenses/
#
# Original Author: Yannick Casamatta (yannick.casamatta@thalesgroup.com)

# Project maintainers must define following variables to adapt this CI to their runtime environment (Settings > CI/CD > Variables)
# - RUN_CV32_CI: 'true'/'false'
# - RUN_CVA6_CI: 'true'/'false'
# - RUN_EXTERNAL_CI: 'true'/'false'
# - EXTERNAL_CI_PROJECT_PATH: custom-group/custom-repo
# - EXTERNAL_CI_PROJECT_BRANCH: dev/mybranch
# - EXTERNAL_CI_YML_PATH: .gitlab-ci/my_custom_ci.yml
# Others users can manually trigger pipelines with overridden variables (CI/CD > Pipeline > Run Pipeline)

# Guidelines:

# - Prefer the use of parent-child pipelines instead of including yml for ease of maintenance.
# - Specific elements should be defined in the triggered yml to avoid conflicts between pipelines.
# - In this file, only generic job/variables should be declared.


variables:
  # Issue gitlab-ci: variables defined here can't be overriden when pipeline is triggered manually or by schedule.
  # Until fix, Avoid setting variables here and prefer set variables in project settings.


# cv32 downstream pipeline 
# If enabled by RUN_CV32_CI, additionnal variables may be necessary and should be declared by project maintainers.
# Please read .gitlab-ci/cv32.yml.
cv32:
  trigger:
    include: .gitlab-ci/cv32.yml
  rules:
    - if: '$RUN_CV32_CI == "true"'
      when: always
    - when: never


# cva6 downstream pipeline
# If enabled by RUN_CVA6_CI, additionnal variables may be necessary and should be declared by project maintainers.
# Please read .gitlab-ci/cva6.yml.
cva6:
  trigger:
    include: .gitlab-ci/cva6.yml
  rules:
    - if: '$RUN_CVA6_CI == "true"'
      when: always
    - when: never


#Use this entry point to run a pipeline from another repository (hosted on the same gitlab server)
# If enabled by RUN_EXTERNAL_CI, additionnal variables may be necessary and should be declared by project maintainers.
external:
  trigger:
    include:
      - project: '$EXTERNAL_CI_PROJECT_PATH'
        ref: '$EXTERNAL_CI_PROJECT_BRANCH'
        file: '$EXTERNAL_CI_YML_PATH'
  variables:
    CVA6_REPO: $CVA6_REPO
    CVA6_BRANCH: $CVA6_BRANCH
    COMPLIANCE_REPO: $COMPLIANCE_REPO
    COMPLIANCE_BRANCH: $COMPLIANCE_BRANCH
    TESTS_REPO: $TESTS_REPO
    TESTS_BRANCH: $TESTS_BRANCH
    TESTS_HASH: $TESTS_HASH
    DV_REPO: $DV_REPO
    DV_BRANCH: $DV_BRANCH
  rules:
    - if: '$RUN_EXTERNAL_CI == "true"'
      when: always
    - when: never
